# Generated by Django 5.2 on 2025-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tech_stack", models.CharField(max_length=200)),
                ("github_url", models.URLField()),
                ("live_demo_url", models.URLField(blank=True)),
            ],
        ),
    ]
